version: "3"

services:

  db:
    image: postgres
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - pp_gdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  app:
      build: .
      tty: true
      ports:
        - "8000:8000"
      command: sh -c "python manage.py migrate && python manage.py runserver 127.0.0.1:8000"
      depends_on:
        db:
          condition: service_healthy
      volumes:
        - .:/app
      env_file:
        - .env

volumes:
  pp_gdata:
