# Generated by Django 5.1.4 on 2025-01-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование стола",
                        max_length=100,
                        verbose_name="Наименование стола",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Опишите стол",
                        max_length=150,
                        verbose_name="Описание стола",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Вставьте фото стола",
                        null=True,
                        upload_to="images/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        help_text="Введите цену за стол", verbose_name="Цена за стол"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="Введите дату создания стола",
                        verbose_name="Дата создания стола в БД",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        help_text="Введите дату изменения стола",
                        verbose_name="Дата изменения стола в БД",
                    ),
                ),
            ],
            options={
                "verbose_name": "стол",
                "verbose_name_plural": "столы",
                "ordering": ["name"],
            },
        ),
    ]
