# Generated by Django 5.1.4 on 2025-01-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tables",
            new_name="Table",
        ),
    ]
