# Generated by Django 5.1.4 on 2025-01-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_rename_tables_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество просмотров",
                verbose_name="Счётчик просмотров",
            ),
        ),
    ]
