# Generated by Django 4.2.2 on 2025-01-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_booking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="table",
        ),
    ]
