# Generated by Django 4.2.2 on 2025-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_remove_booking_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="user",
            new_name="name",
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
    ]
